# Generated by Django 2.1.1 on 2018-09-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_post_detail_post_title_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text_line', models.TextField(max_length=500)),
                ('mail_id', models.CharField(max_length=100)),
                ('about_image', models.FileField(upload_to='about/')),
            ],
        ),
    ]
