# Generated by Django 2.1.1 on 2018-09-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_about_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contain', models.CharField(max_length=250)),
                ('Our_Customers_image', models.FileField(upload_to='about/')),
            ],
        ),
    ]
