# Generated by Django 2.1.1 on 2018-09-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_our_customers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Our_Customers',
            new_name='Commenter_Name',
        ),
    ]
