# Generated by Django 2.1.1 on 2018-10-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_our_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Phone_Number', models.DecimalField(decimal_places=2, max_digits=13)),
                ('Email_Address', models.CharField(max_length=100)),
                ('Message', models.TextField(max_length=5000)),
            ],
        ),
    ]
