# Generated by Django 2.0.7 on 2018-08-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180810_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='image_url',
            field=models.ImageField(upload_to='media/imag'),
        ),
    ]
