# Generated by Django 2.0.7 on 2018-08-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180810_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='image_url',
            field=models.FileField(upload_to='media/imag'),
        ),
    ]
