# Generated by Django 2.0.7 on 2018-08-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180810_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='image_url',
            field=models.FileField(upload_to='imag'),
        ),
    ]
