# Generated by Django 2.0.7 on 2018-08-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180810_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('textbox', models.CharField(max_length=1000)),
                ('image_product', models.FileField(upload_to='imagepro/')),
            ],
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='location',
            field=models.CharField(max_length=1000),
        ),
    ]
